-- MySQL Script generated by MySQL Workbench
-- 03/03/16 13:10:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOSTutors` DEFAULT CHARACTER SET latin1 ;
USE `SOSTutors` ;

-- -----------------------------------------------------
-- Table `SOSTutors`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`sessions` (
  `sessionID` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(15) NULL,
  `content` VARCHAR(100) NULL,
  `date_posted` DATE NULL,
  `booking_available` TINYINT(1) NOT NULL DEFAULT 1,
  `booking_date` DATE NULL,
  `booking_location` VARCHAR(45) NULL,
  `tutors_tutorID` INT NULL,
  `students_studentID` VARCHAR(45) NULL,
  `categories_categoryID` INT NULL,
  PRIMARY KEY (`sessionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`comments` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `content` VARCHAR(100) NULL,
  `date_posted` DATE NULL,
  `tutors_tutorID` INT NULL,
  `students_studentID` VARCHAR(45) NULL,
  PRIMARY KEY (`commentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`students` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `profile` VARCHAR(100) NULL,
  `language` VARCHAR(10) NULL,
  `date_joined` DATE NULL,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`tutors` (
  `tutorID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `profile` VARCHAR(100) NULL,
  `hourly` VARCHAR(15) NULL,
  `rating` VARCHAR(15) NULL,
  `date_joined` DATE NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`tutorID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`notifications` (
  `notificationID` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `content` VARCHAR(100) NULL,
  `date_posted` DATE NULL,
  `tutors_tutorID` INT NULL,
  `students_studentID` INT NULL,
  `sessions_sessionID` INT NULL,
  PRIMARY KEY (`notificationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`categories` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `subjectEN` VARCHAR(45) NULL,
  `subjectFR` VARCHAR(45) NULL,
  `descriptionEN` VARCHAR(100) NULL,
  `descriptionFR` VARCHAR(100) NULL,
  `language` VARCHAR(15) NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
