-- MySQL Script generated by MySQL Workbench
-- 02/20/16 10:57:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOSTutors` DEFAULT CHARACTER SET latin1 ;
USE `SOSTutors` ;

-- -----------------------------------------------------
-- Table `SOSTutors`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`sessions` (
  `sessionID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(144) NULL,
  `content` VARCHAR(100) NULL,
  `date_published` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `bookings_bookingID` INT NULL,
  `tutors_tutorID` INT NULL,
  `categories_categoryID` INT NULL,
  PRIMARY KEY (`sessionID`, `bookings_bookingID`, `tutors_tutorID`, `categories_categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`comments` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`commentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`students` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `profile` VARCHAR(45) NULL,
  `date_joined` DATE NULL,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`tutors` (
  `tutorID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `profile` VARCHAR(100) NULL,
  `hourly` VARCHAR(15) NULL,
  `rating` VARCHAR(15) NULL,
  `date_joined` DATE NULL,
  PRIMARY KEY (`tutorID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`bookings` (
  `bookingID` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  `confirmed` TINYINT(1) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`bookingID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`notifications` (
  `notificationID` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `content` VARCHAR(100) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`notificationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`categories` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `subjectEN` VARCHAR(45) NULL,
  `subjectFR` VARCHAR(45) NULL,
  `descriptionEN` VARCHAR(45) NULL,
  `descriptionFR` VARCHAR(45) NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO students(email,password,fname,lname,profile,date_joined) VALUES ('student1@here.com', 'password','John', 'Doe', 'Hi, this is my profile.', '2016-02-03');
INSERT INTO students(email,password,fname,lname,profile,date_joined) VALUES ('student2@here.com', 'password','Jane', 'Doe', 'Hi, this is my profile.', '2016-01-13');
INSERT INTO tutors(email,password,fname,lname,profile,hourly,rating,date_joined) VALUES ('tutor1@here.com', 'password', 'Jake', 'Smith', 'Hi, this is my profile.', '15', '5', '2016-01-11');
INSERT INTO tutors(email,password,fname,lname,profile,hourly,rating,date_joined) VALUES ('tutor2@here.com', 'password', 'Jane', 'Smith', 'Hi, this is my profile.', '15', '5', '2016-02-03');