-- MySQL Script generated by MySQL Workbench
-- 02/08/16 21:58:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOSTutors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOSTutors` DEFAULT CHARACTER SET latin1 ;
USE `SOSTutors` ;

-- -----------------------------------------------------
-- Table `SOSTutors`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`students` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `date_joined` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  PRIMARY KEY (`studentID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`bookings` (
  `bookingID` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  `confirmed` TINYINT(1) NULL,
  `location` VARCHAR(45) NULL,
  `students_studentID` INT NOT NULL,
  PRIMARY KEY (`bookingID`, `students_studentID`),
  INDEX `fk_bookings_students1_idx` (`students_studentID` ASC),
  CONSTRAINT `fk_bookings_students1`
    FOREIGN KEY (`students_studentID`)
    REFERENCES `SOSTutors`.`students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`tutors` (
  `tutorID` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `hourly` VARCHAR(45) NULL,
  `rating` VARCHAR(45) NULL,
  `password` VARCHAR(32) NOT NULL,
  `date_joined` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  PRIMARY KEY (`tutorID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`sessions` (
  `sessionID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(144) NULL,
  `content` TEXT NULL,
  `date_published` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  `bookings_bookingID` INT NOT NULL,
  `tutors_tutorID` INT NOT NULL,
  PRIMARY KEY (`sessionID`, `bookings_bookingID`, `tutors_tutorID`),
  INDEX `fk_sessions_bookings1_idx` (`bookings_bookingID` ASC),
  INDEX `fk_sessions_tutors1_idx` (`tutors_tutorID` ASC),
  CONSTRAINT `fk_sessions_bookings1`
    FOREIGN KEY (`bookings_bookingID`)
    REFERENCES `SOSTutors`.`bookings` (`bookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessions_tutors1`
    FOREIGN KEY (`tutors_tutorID`)
    REFERENCES `SOSTutors`.`tutors` (`tutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`comments` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `comment` TEXT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `students_studentID` INT NOT NULL,
  `sessions_sessionID` INT NOT NULL,
  `sessions_bookings_bookingID` INT NOT NULL,
  `sessions_tutors_tutorID` INT NOT NULL,
  PRIMARY KEY (`commentID`, `students_studentID`, `sessions_sessionID`, `sessions_bookings_bookingID`, `sessions_tutors_tutorID`),
  INDEX `fk_comments_students1_idx` (`students_studentID` ASC),
  INDEX `fk_comments_sessions1_idx` (`sessions_sessionID` ASC, `sessions_bookings_bookingID` ASC, `sessions_tutors_tutorID` ASC),
  CONSTRAINT `fk_comments_students1`
    FOREIGN KEY (`students_studentID`)
    REFERENCES `SOSTutors`.`students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_sessions1`
    FOREIGN KEY (`sessions_sessionID` , `sessions_bookings_bookingID` , `sessions_tutors_tutorID`)
    REFERENCES `SOSTutors`.`sessions` (`sessionID` , `bookings_bookingID` , `tutors_tutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOSTutors`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOSTutors`.`notifications` (
  `notificationID` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `students_studentID` INT NOT NULL,
  `tutors_tutorID` INT NOT NULL,
  PRIMARY KEY (`notificationID`, `students_studentID`, `tutors_tutorID`),
  INDEX `fk_notifications_students1_idx` (`students_studentID` ASC),
  INDEX `fk_notifications_tutors1_idx` (`tutors_tutorID` ASC),
  CONSTRAINT `fk_notifications_students1`
    FOREIGN KEY (`students_studentID`)
    REFERENCES `SOSTutors`.`students` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_tutors1`
    FOREIGN KEY (`tutors_tutorID`)
    REFERENCES `SOSTutors`.`tutors` (`tutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO tutors(fname,email,password,date_joined,lname) VALUES ('Wise', 'tutor@here.com', 'password', '3 Feb 2016', 'Guy');
INSERT INTO tutors(fname,email,password,date_joined,lname) VALUES ('Ms', 'tutor2@here.com', 'password', '3 Feb 2016', 'Knowitall');